#!/bin/sh

# Get current dir
PREVIOUS_DIR="$PWD"

# Get directory this script is located in
PROGRAM_DIR="$( cd "$( dirname "$0" )" && pwd )"

# Enter program directory
cd $PROGRAM_DIR

# Run the program
java -jar asteria.jar --server $@

# Return to previous dir
cd $PREVIOUS_DIR

